### ISSUE TITLE
Api 10

### ISSUE THREAD

**Issue by yoavst** [JorgeCastilloPrz/FABProgressCircle#1]
Is it possible to support?

**Comment by JorgeCastilloPrz** [comment]
I am sorry, but the current animation API was added in Honeycomb (API 11) and to port this code backwards would need a switch to NineOldAndroids. I am not planning to do that atm.

**Comment by yoavst** [comment]
Ok, thanks for explaining the reason. If I would split the project to 3 libs - base (shared code), nineoldandroid and stock, will you approve the pull request?

**Comment by JorgeCastilloPrz** [comment]
I dont think so, as it would be not easy to maintain. I will keep it like
it is right now until more people ask for the same feature.

Sorry.

**Comment by yoavst** [comment]
It looks like the only change that is not nineoldandroid is `setAlpha`, which can be changed to `ViewCompat.setAlpha` from support v4.

**Comment by JorgeCastilloPrz** [comment]
As i tould you before,  NineOldAndroids would be totally needed as
ObjectAnimator / ValueAnimator... Etc are not supported in API 10.

**Comment by yoavst** [comment]
yea, I wrote it for people who would look on this issue in the future

**Comment by JorgeCastilloPrz** [comment]
:+1: it's ok.
