### ISSUE TITLE
Make a progress version

### ISSUE THREAD

**Issue by AdrianVovk** [JorgeCastilloPrz/FABProgressCircle#11]
I'm making a music player and a version where I set a max value and it fills it up. Like a rounded progress bar

**Comment by AndroidDeveloperLB** [comment]
@AnimbusDev I think one of those libraries could fit your needs (under "Progress Indicators" ) :
https://android-arsenal.com/free

**Comment by roman-ku** [comment]
None of those "Progress Indicators" have a floating action button that can show both definite and indefinite progress.

There are several libraries I found but none of them do both:

Only indefinite:
- this one
- [Circular loader integrated with a floating action button by Dmitry Malkovich](https://github.com/DmitryMalkovich/circular-with-floating-action-button)

Only definite:
- [ProgressFloatingActionButton by Daniel Mallcott](https://github.com/dmallcott/ProgressFloatingActionButton)

That being said there actually one that does both but it's not based on the Floating Action Button provided in the support library: [FabProgress by Kurt Mbanje](https://github.com/ckurtm/FabButton)

**Comment by AndroidDeveloperLB** [comment]
I only tried to help.

**Comment by roman-ku** [comment]
Thanks man. Wish there was a good solution for this out there.

I will try that FAB library by @ckurtm. Hopefully it works out.
