### ISSUE TITLE
Listener for full cycle of animation

### ISSUE THREAD

**Issue by yoavst** [JorgeCastilloPrz/FABProgressCircle#2]
When it fails, I want to wait to the animation to finish the circle before `hide()` it. 
Is there a way to do that?

**Comment by JorgeCastilloPrz** [comment]
I am adding the reset feature after finish in version 1.01. Stay tunned :)

**Comment by ares89** [comment]
I also wanna reset the FABprogresscircle after the finalAnimation.
Thank you!

**Comment by JorgeCastilloPrz** [comment]
1.01 will be done and published today.

**Comment by JorgeCastilloPrz** [comment]
This issue and all issues related to this one have been fixed in patch 1.01. You already can download it.
```groovy
dependencies{
    compile 'com.github.jorgecastilloprz:fabprogresscircle:1.01@aar'
}
```
or 
```xml
<dependency>
    <groupId>com.github.jorgecastilloprz</groupId>
    <artifactId>fabprogresscircle</artifactId>
    <version>1.01</version>
    <type>aar</type>
</dependency>
```

**Comment by yoavst** [comment]
It is good attribute, but it isn't what I've wanted. But it is good enough though so it is ok for me.

**Comment by JorgeCastilloPrz** [comment]
if you want to hide it after the animation ends, just call hide() into the listener call. Is that what you tried to mean?:

```java
@Override public void onFABProgressAnimationEnd() {
    mProgressCircle.hide();
}
```

**Comment by JorgeCastilloPrz** [comment]
Ok, i think i dit not understand you the first time i read your message. I will think about adding that feature into the next patch, if more people ask me to.

**Comment by JorgeCastilloPrz** [comment]
Hi again. Could you describe the effect you are looking for a little bit more? I want to think about it for the next patch and i am not pretty sure about what you mean. 

Thanks in advance and thanks for the feedback.

**Comment by yoavst** [comment]
Sorry, I was away from home.
there is the circle loading animation. When you want to finish it, first it finish the circle to full 100%. In this case I would like to receive the event, for cases I don't want the `V` drawable for the FAB
